---
- name: Restart service prometheus
  ansible.builtin.systemd:
    name: prometheus.service
    state: restarted
  ignore_errors: '{{ ansible_check_mode }}'

- name: Reload service prometheus
  ansible.builtin.systemd:
    name: prometheus.service
    state: reloaded
  ignore_errors: '{{ ansible_check_mode }}'
